# Postgres password should be masked in CI and in production
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Password001+'
      POSTGRES_USER: "scrapReality"
      POSTGRES_DB: "scrapDb"
    ports:
      - 5432:5432

  app:
    build: build
    environment:
      POSTGRES_PASSWORD: 'Password001+'
      POSTGRES_USER: "scrapReality"
      POSTGRES_DB: "scrapDb"
      POSTGRES_HOST: "database"
      POSTGRES_PORT: 5432
      APP_PORT: 8080
    restart: always
    links:
      - db:database
    depends_on:
      - db
    volumes:
      - .:/app
    expose:
      - 8080
    ports:
      - 8080:8080
