# Postgres password should be masked in CI and in production
version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 'Password001+'
      POSTGRES_USER: "scrapReality"
      POSTGRES_DB: "scrapDb"
    ports:
      - 5432:5432

  app:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    environment:
      POSTGRES_PASSWORD: 'Password001+'
      POSTGRES_USER: "scrapReality"
      POSTGRES_DB: "scrapDb"
      POSTGRES_HOST: "database"
      POSTGRES_PORT: 5432
      APP_PORT: 8080
      MONGO_HOST: "mongo:27017"
    restart: always
    links:
      - db:database
    depends_on:
      - mongo
    volumes:
      - .:/app
    expose:
      - 8080
    ports:
      - 8080:8080
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "scrapReality"
      MONGO_INITDB_ROOT_PASSWORD: "Password001+"
    ports:
      - 27017:27017

