# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Basic workflow
on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

jobs:
  testing:

    runs-on: python3.9
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: |
        make dev-build
    - name: Mypy checks
      run: |
        make type-check
    - name: Pylint checks
      run: |
        make pylint-check
    - name: Tests
      run: |
        make tests